databases:
  - name: brohealth-db
    plan: free
    databaseName: brohealth_db
    user: brohealth_admin

services:
  - type: web
    plan: free
    name: brohealth-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p ${PORT} brohealth.asgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brohealth-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    envFile: .env
    envVarFile: .env
    staticPublishPath: static
    staticConf:
      ROOT: staticfiles
    resources:
      instanceCount: 1
  - type: worker
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A brohealth worker --beat --scheduler django --loglevel=info
    envFile: .env
    envVarFile: .env