services:
  - name: brohealth-backend
    env: python 
    type: web
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      daphne -b 0.0.0.0 -p ${PORT} brohealth.asgi:application
      celery -A brohealth worker --loglevel=info
      celery -A brohealth beat --scheduler django --loglevel=info
