services:
  - type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p ${PORT} brohealth.asgi:application
    envFile: .env
    envVarFile: .env
    staticPublishPath: static
    staticConf:
      ROOT: staticfiles
    resources:
      instanceCount: 1
  - type: worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A brohealth worker --beat --scheduler django --loglevel=info
    envFile: .env
    envVarFile: .env
databases:
  - type: postgresql
    plan: starter