# Generated by Django 5.0.2 on 2024-03-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appointmentroom_appointmentchat"),
        ("doctors", "0006_remove_doctor_consultation_fee"),
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_given",
                to="doctors.doctor",
            ),
        ),
    ]
