# Generated by Django 5.0.2 on 2024-03-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0003_prescription_prescription_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
