# Generated by Django 5.0.2 on 2024-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_consultation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
