# Generated by Django 5.0.2 on 2024-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_options_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['doctor'], 'verbose_name': 'doctor availability', 'verbose_name_plural': 'doctor availabilities'},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='availability_schedule',
            field=models.JSONField(default=dict),
        ),
    ]
