# Generated by Django 5.0.2 on 2024-03-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctoravailability_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
