# Generated by Django 5.0.2 on 2024-03-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_doctor_consultation_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="consultation_fee",
        ),
    ]
